services:
  moth:
    build: .
    container_name: moth
    restart: unless-stopped
    ports:
      - "${MOTH_PORT:-6969}:8000"
    volumes:
      - ./data:/data
      - C:/Users/LCAC/Downloads/Media:/media
      - "${MOTH_TRASH_PATH}:/moth/trash"
    env_file: .env
